//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int UserId { get; set; }
        public int TiffinTypeId { get; set; }
        public bool IsButterMilk { get; set; }
        public int TiffinPrice { get; set; }
        public int ButterMilkPrice { get; set; }
        public string ExtraItem { get; set; }
        public Nullable<int> ExtraItemPrice { get; set; }
        public int Total { get; set; }
    
        public virtual TiffinTypeMaster TiffinTypeMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
